name: heathernoe
favicon: null
layout_spectrum: 0.09189290879294276
typography_spectrum: 0.61312
title: Heather Noe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76627d'
    - '#614665'
    - '#7e4d84'
    - '#7c6e87'
    - '#85598c'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
